In [17]:
import numpy as np

# Question 1

In [17]:
np.random.rand(3,4)

array([[2.22519657e-01, 2.68652021e-01, 8.33565281e-01, 1.50599964e-01],
       [4.97322236e-02, 1.07648484e-04, 4.10922245e-01, 3.68379776e-01],
       [1.76963277e-01, 2.65971378e-01, 7.39824923e-01, 4.54829902e-01]])

# Question 2

In [20]:
a1 = [1,2,3,4,5,6]
ar= np.array(a1)

In [22]:
ar

array([1, 2, 3, 4, 5, 6])

In [23]:
ar[2]

3

In [25]:
ar[0:3]

array([1, 2, 3])

In [26]:
ar[4]=9

In [27]:
ar

array([1, 2, 3, 4, 9, 6])

In [31]:
list1= [1,2,3,4,5]
list2= [3,4,5,6,7]
list3= [5,6,7,8,9]

ar1= np.array([list1, list2, list3])

In [32]:
ar1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [33]:
ar1.shape

(3, 5)

# Question 3 

In [34]:
b= np.ones ([3,2])

In [35]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
import numpy as np

In [6]:
np.full ((2,3), 65)

array([[65, 65, 65],
       [65, 65, 65]])

In [36]:
c= np.identity(2)

In [37]:
c

array([[1., 0.],
       [0., 1.]])

# Question 4

In [21]:
a1= np.array ([[10,20,30,40],[11,22,33,44],[12,23,34,45]])
a1

array([[10, 20, 30, 40],
       [11, 22, 33, 44],
       [12, 23, 34, 45]])

In [29]:
a1[0:2, 1:3]

array([[20, 30],
       [22, 33]])

# Question 5

In [8]:
x= np.array([[1,2],[3,4]], dtype=np.float64)
y= np.array([[5,6],[7,8]], dtype=np.float64)


In [11]:
np.sum(x+y)

36.0

In [14]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [15]:
np.multiply(x,y)

array([[ 5., 12.],
       [21., 32.]])

In [16]:
np.sqrt(x,y)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

# Question 6

In [1]:
import numpy as np

In [3]:
v = np.array([1, 0, 1])
np.stack ((v,v,v,v))

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [20]:
x= np.array([1,2,3])
np.tile(x,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

# Question 7

In [30]:
odd= np.arange(1,11)
   for i in odd
    if (i % 2 != 0):
        print(i, end = "  ")

IndentationError: unexpected indent (1108749602.py, line 2)

# Question 8

In [ ]:
a = np.arange(10).reshape((2, 5))

In [32]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
a.shape

(2, 5)

In [34]:
a = np.array([[1, 2, 3], [3, 4, 5]])
list(a)

[array([1, 2, 3]), array([3, 4, 5])]

In [35]:
a.tolist()

[[1, 2, 3], [3, 4, 5]]

In [36]:
list = [1, 2, 3, 4, 5, 6, 7]
np.array(list)


array([1, 2, 3, 4, 5, 6, 7])

# Question 9

In [52]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0

In [53]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Question 10

In [58]:
x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1

In [59]:
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])