In [2]:
import numpy as np

# Create a 5x5 matrix with row values ranging from 0 to 4

In [3]:
x = np.zeros((5,5))
x += np.arange(5)

In [4]:
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [5]:
x = np.random.random((5,3))

In [6]:
x

array([[0.26330251, 0.91258366, 0.5442374 ],
       [0.8811686 , 0.36824915, 0.9841451 ],
       [0.62407566, 0.69134378, 0.25341107],
       [0.12898759, 0.64945652, 0.53686964],
       [0.74560342, 0.98772621, 0.44378351]])

In [7]:
y = np.random.random((3,2))

In [8]:
y

array([[0.23860334, 0.00918846],
       [0.06837976, 0.46780928],
       [0.98930998, 0.92363534]])

In [9]:
np.dot(x, y)

array([[0.6636466 , 0.93201135],
       [1.20905513, 1.08935814],
       [0.44688256, 0.56321075],
       [0.60631704, 0.80087875],
       [0.6844834 , 0.87881256]])

#  What is the result of the following expression?

In [10]:
#0 * np.nan

In [11]:
y = np.random.random((3,2))

In [12]:
y

array([[0.51418276, 0.88620261],
       [0.68522191, 0.34473519],
       [0.4456957 , 0.76626735]])

In [14]:
y

nan

In [16]:
a_nan = np.array([0, 1, np.nan, float('nan')])

In [17]:
a_nan

array([ 0.,  1., nan, nan])

In [18]:
np.nan == np.nan

False

In [19]:
np.inf > np.nan

False

In [20]:
np.nan - np.nan

nan

In [21]:
np.nan in set([np.nan])


True

In [22]:
0.3 == 3 * 0.1

False

# Create a 10x10 array with random values and find the minimum and maximum values

In [23]:
y = np.random.random((10,10))

In [24]:
y

array([[0.00120033, 0.6493018 , 0.77224764, 0.88449671, 0.25512657,
        0.80102537, 0.98300917, 0.78399721, 0.64820392, 0.86366088],
       [0.11909507, 0.40276469, 0.20775275, 0.72142992, 0.94836106,
        0.50573238, 0.73368439, 0.88309561, 0.78866278, 0.78563276],
       [0.34230233, 0.27689365, 0.90124631, 0.16697831, 0.36947253,
        0.61306223, 0.79009362, 0.52059954, 0.68865202, 0.88417308],
       [0.54222783, 0.97953994, 0.54243008, 0.64830913, 0.17473424,
        0.59213479, 0.72631385, 0.51276099, 0.11023196, 0.86451104],
       [0.55230957, 0.07541632, 0.28754222, 0.29122791, 0.94348416,
        0.24976904, 0.39793527, 0.25470358, 0.78013709, 0.04168539],
       [0.30949095, 0.98780303, 0.74347178, 0.30357174, 0.37953159,
        0.37804548, 0.21613336, 0.50025438, 0.67601835, 0.31202481],
       [0.44636348, 0.10384524, 0.62989038, 0.85118736, 0.69107614,
        0.92803544, 0.31067004, 0.25025017, 0.63908973, 0.09720911],
       [0.33562772, 0.60162883, 0.2687634

In [28]:
np.max(y)

0.9878030340246997

In [30]:
np.min(y)

0.0012003255390782286

#  Create a null vector of size 10 but the fifth value which is 1 

In [31]:
np.arange(10) == 4

array([False, False, False, False,  True, False, False, False, False,
       False])

In [34]:
np.arange(10) * 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
z = np.zeros(10)

In [37]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
z[4] = 1

In [39]:
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])